### ISSUE TITLE
Feature request: open generated code on online compiler

### ISSUE THREAD

**Issue by MaximGalkin-TomTom** [rijnb/chatty-server#120]
To validate correctness of a generated code and to use it as a base of further experiments, it would be useful to have a button "Compile" next to existing "Download" and "Copy" on a code window.
There are different free online compilers available for majority of programming languages.
As we would not like to share TomTom code to online tools outside TomTom, only generated code should be "openable" in this feature.

**Comment by oleksiikulyk-tomtom** [comment]
Thanks for the idea @MaximGalkin-TomTom 
there are indeed dozens of online tools available. Do you have "preferred" in mind?

I'm also curious when/how often it can be used. It hardly ever creates a single complete compileable useful unit of code (based on my personal anecdotal evidence of course). What case do you have in mind?

**Comment by RijnBuve-TomTom** [comment]
Closing the request, as individual pieces of code are unlikely to compile stand-alone (lacking their dependencies). I recommend using Copilot for real code experiments instead.
