### ISSUE TITLE
Scrollbar slider is unclickable behind transparent gradient layer

### ISSUE THREAD

**Issue by FelixDombek-TomTom** [rijnb/chatty-server#122]
The lower part of the scrollbar vanishes behind the shaded area in which the prompt textfield sits. When the scrollbar slider is long, this is not a problem -- they stick out at the top. But for very small scrollbar sliders, there is no way to click them anymore.

![image](https://github.com/rijnb/chatty-server/assets/77961370/29586efe-5ddb-4bee-892c-ce25cd233f9c)

**Comment by RijnBuve-TomTom** [comment]
Fixed
