### ISSUE TITLE
Feature Request: Can I provide query as a URL param?

### ISSUE THREAD

**Issue by arunjoseph-tomtom** [rijnb/chatty-server#130]
Provide steps to reproduce the problem here...

I am using web browser plugin to search sites directly from address bar. I can add chatty as quick search option but requires to support query in URL.

<img width="500" alt="image" src="https://github.com/rijnb/chatty-server/assets/83452786/f9e33bb1-e525-4aab-ade1-c6d2b7950777">

**Comment by rijnb** [comment]
Chatty is not a search itself. It does not produce multiple “results” as a search engine would. It produces 1 answer to 1 question. Adding Chatty as a search engine would probably yield worse results than just entering the text in Chatty itself (which also takes the history of your conversation into account).
Perhaps more useful than adding Chatty as a search engine is using the built-in option to use Google Search and have Chatty interpret the results. You can use that by entering your Google Search API key and your Google CSE ID,
