### ISSUE TITLE
Feature Request: Update training data

### ISSUE THREAD

**Issue by arunjoseph-tomtom** [rijnb/chatty-server#131]
Looks like the training data is until October 2021, It will be great if the training data is up to date.

**Comment by rijnb** [comment]
Agreed, but Chatty does not include the ChatGPT back-end server. It’s just the front-end to existing ChatGPT servers. So please direct the request to the ChatGPT server you’re using (such as TomTom’s internal instance, if you’re using TomTom’s Azure instance).
