### ISSUE TITLE
Formula / equations are printed out as plain Latex instead of being rendered

### ISSUE THREAD

**Issue by MatteoMecucci-TomTom** [rijnb/chatty-server#133]
Ask to write a formula, like "what's the formula for compound interest?", and you'll get Latex plain text instead of the rendered Latex as you get in regular ChatGPT: something like "[ A = P \times \left(1 + \frac{r}{n}\right)^{nt} ]".

**Comment by MatteoMecucci-TomTom** [comment]
Sorry, I need to reopen this after some more testing. Look at this one:
![Screenshot 2023-10-24 at 15 54 02](https://github.com/rijnb/chatty-server/assets/69153859/3ef61083-35a9-491d-9dd9-2678c08d031d)
![Screenshot 2023-10-24 at 15 54 16](https://github.com/rijnb/chatty-server/assets/69153859/fde2b989-4817-41e6-b465-2d687d29f69a)

**Comment by RijnBuve-TomTom** [comment]
Screenshot from Chatty:

<img width="767" alt="Scherm­afbeelding 2023-10-24 om 16 21 44" src="https://github.com/rijnb/chatty-server/assets/72975877/514f6352-32fc-4555-a5a3-f2c947403233">

What is wrong with this?

**Comment by RijnBuve-TomTom** [comment]
The difference is visible for LaTeX rendering:

<img width="847" alt="Scherm­afbeelding 2023-10-24 om 16 25 32" src="https://github.com/rijnb/chatty-server/assets/72975877/897a070d-6681-47f9-bf60-b18db1d997e5">

**Comment by RijnBuve-TomTom** [comment]
Fixed
