### ISSUE TITLE
Missing CJK Font

### ISSUE THREAD

**Issue by howieyu-tomtom** [rijnb/chatty-server#183]
![Screenshot 2024-04-07 at 2 23 08 PM](https://github.com/rijnb/chatty-server/assets/93319702/f8da2c77-1312-4a0d-97e6-e55203b8ab2c)

The CJK language such as Chinese cannot show properly.

**Comment by RijnBuve-TomTom** [comment]
Confirmed. This bug is an unwanted side effect of the latest fix to avoid the renderer crashing on strange input. Need to fix.

**Comment by RijnBuve-TomTom** [comment]
Pushed and deployed a better fix for the math crashes. Non-ASCII chars are only replaced with [?] now if they are enclosed in $-signs. Otherwise, they are just rendered.
