### ISSUE TITLE
Problem with utf-8/non-ascii characters display

### ISSUE THREAD

**Issue by alexeisolodovnicov-tomtom** [rijnb/chatty-server#184]
Previously it was all good, but starting from today I can see that in the main chat non-ascii characters are displayed incorrectly. In the history on the left side, and in the prompt on the right side it's all good, same as in the text field of the chat, but the chat itself doesn't display the symbols correctly:

![image](https://github.com/rijnb/chatty-server/assets/93539641/5b77d729-9b21-4c55-ac45-2cba6433a37a)

**Comment by RijnBuve-TomTom** [comment]
Confirmed. This bug is an unwanted side effect of the latest fix to avoid the renderer crashing on strange input. Need to fix.

**Comment by RijnBuve-TomTom** [comment]
Pushed and deployed a better fix for the math crashes. Non-ASCII chars are only replaced with [?] now if they are enclosed in $-signs. Otherwise, they are just rendered.
