### ISSUE TITLE
gpt 4 takes very long and most importantly hangs up almost every time.

### ISSUE THREAD

**Issue by NilsHampe-TomTom** [rijnb/chatty-server#186]
Usually it only hangs up sometimes but right now it is almost always. It then shows connection error and sops mid answer. I could imagine that it has to do with peak and off-peak hours.

**Comment by RijnBuve-TomTom** [comment]
Hi Nils, this behaviour is caused not by the Chatty front-end, but by the GPT-4 instance that it's using. This open-source project only addresses problems with the front-end. Latency and responsiveness issues for the GPT-4 model are handled through CCoE (for TomTom deployments). Please raise this issue in the `tomtom-chatgpt` Slack channel to be heard there. Thanks!

**Comment by NilsHampe-TomTom** [comment]
I see. Thanks for the response. And btw, incredible work, in general this is insanely helpful!!
