### ISSUE TITLE
Expand the ability to use internal data

### ISSUE THREAD

**Issue by illiamatviienko-tomtom** [rijnb/chatty-server#216]
Similar to the solution in this blog (https://tech.deliveryhero.com/employeegpt-leveraging-ai-for-internal-knowledge-discovery/), we can enable anyone at tomtom to quickly answer questions from the internal sources such as
- What POI categories do we have? What are the mandatory attributes?
- How many roads are covered in Germany in our map?
These and similar trivial questions are often asked by non-tech customer facing teams and steal time of the development teams answering them because customer-facing teams are not equipped with easy to use tools.

**Comment by RijnBuve-TomTom** [comment]
We are working on seeing how/if we can integrate AI tooling with our internal knowledge systems. This is however a feature of the deployed model; not of Chatty. Hence closing this feature request. Please feel free to contact CCOE in TomTom for this as well.
