### ISSUE TITLE
I would like to upload documents with texts

### ISSUE THREAD

**Issue by WendyVanthiel-TomTom** [rijnb/chatty-server#219]
I would really like to upload transcripts of meetings in order for chatty to really learn quickly about certain topics so I can later on use it as a sparring partner

**Comment by RijnBuve-TomTom** [comment]
Just type "/drop" in the prompt and you will get a dialog where you drop your text files for questioning.

**Comment by WendyVanthiel-TomTom** [comment]
[like]  Wendy van Thiel reacted to your message:
________________________________
