### ISSUE TITLE
Dynamic model selection is not working for Azure OpenAI

### ISSUE THREAD

**Issue by olkulyk** [rijnb/chatty-server#23]
The model name provided as a part of completion request is not applicable to Azure OpenAI, where deployment information should be included in the Azure resource URI that's connected to.

https://github.com/rijnb/chatty-server/blob/bce5d678fcdb5e37accb34e4297663e574f57230/utils/server/index.ts#L39

**Comment by olkulyk** [comment]
The API to fetch available deployments (hence models) was removed (https://github.com/openai/openai-python/issues/460#issuecomment-1569290683) from Azure API versions 2023-05-15 and newer in favor of [cognitiveservices api](https://learn.microsoft.com/en-us/rest/api/cognitiveservices/accountmanagement/deployments/list?tabs=HTTP) which seems an overkill.
I see the following options
1. Disable model selection (for now)
2. Configure explicitly deployment for every model
3. Assume deployment naming convention (convention over configuration)

**Comment by RijnBuve-TomTom** [comment]
We've fixed it using option 3 - naming convention for Azure.
