### ISSUE TITLE
Shared prompt library

### ISSUE THREAD

**Issue by FerencSzeli-TomTom** [rijnb/chatty-server#29]
Prompts are everything. I am writing my own prompts, but it would be cool to share them with the community and also download / use what others created. Lastly, maybe some can be curated and made "factory".

**Comment by RijnBuve-TomTom** [comment]
As for the implementation, I'm thinking for example this could be like allowing you to "subscribe" to one or more Github repo's that contain shared prompts. Anyone can provide edited prompts there and they would be auto-imported.

**Comment by RijnBuve-TomTom** [comment]
Added support for "local" prompts for a specific deployment. These can be added to `factory-prompts-local.json` in the deployment. This 'partially' fixes the request.

**Comment by RijnBuve-TomTom** [comment]
Closing the request as `factory-prompts-local.json` are now supported.
