### ISSUE TITLE
Factory Prompts are cloned even if no changes are made

### ISSUE THREAD

**Issue by olkulyk** [rijnb/chatty-server#32]
How to reproduce:
1. Click on factory prompt to go into Edit mode
2. Click away without making any changes

Expectations: no clone is created.

Question: shouldn't edited prompt replace factory? :thinking:

**Comment by RijnBuve-TomTom** [comment]
Clicking outside the box is the same as "Save" for this dialog. But it should not create a user prompt if it is not changed.
Factory prompts are never replaced. I'd like to keep them "immutable" for now, so they can always be bulk-updated at the reload of the page. 
Change to make: to do not save if the content of the prompt did not change. Name may be the same though.

**Comment by RijnBuve-TomTom** [comment]
Factory prompts are now read-only. If you change them, the change must be more than just a whitespace. And it will create a user prompt.
