### ISSUE TITLE
Inconsistent Factory Prompts & Folders behavior

### ISSUE THREAD

**Issue by olkulyk** [rijnb/chatty-server#33]
User cannot delete Factory prompts (by design).

1. When I try to rearrange factory prompts to other folders (by dragging and dropping) the clone is created, factory prompt remains in the source folder unchanged.
![image](https://github.com/rijnb/chatty-server/assets/12675197/851cf6f8-c9a4-4ee3-ada8-650ab1a19750)

2. It is possible to delete "Factory Folders". In this case the content (incl factory prompts) is moved to root. It's not possible to rearrange them due to point 1 leaving the user stranded. the only way out of it is to reset

**Comment by RijnBuve-TomTom** [comment]
1. Prompt should not be recreated. Bug.
2. Factory folders should not be editable/deleted. Bug.

**Comment by RijnBuve-TomTom** [comment]
Refactored factory folders and prompts to be read-only.
