### ISSUE TITLE
"Stop generating" does not work when the server 'hangs' after sending a request, before streaming an answer

### ISSUE THREAD

**Issue by rijnb** [rijnb/chatty-server#55]
Sometimes, when you send a promt and the Robot icon turns green, receiving a request may take endlessly and hangs. Stop generating does not work at that moment, leaving the UI unusable. May be that the Azure server fails or so, but the UI doesn't handle it.

**Comment by RijnBuve-TomTom** [comment]
Improved error/timeout handling.
